### PR TITLE
Test Travis with Ember try:one for visual-acceptance

### PR DESCRIPTION
**Pull request by EWhite613**
Use ember-cli-visual-acceptance. Add new test to check for input file upload.

#patch#

### CODE REVIEW

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by sglanzer** [comment]
Is there any way we replace the previous image comment when new commits go in so that we don't end up with multiple image comments?

**Comment by sglanzer** [comment]
Where is the box on the right of the Browser coming from?

**Comment by EWhite613** [comment]
@sglanzer We could, would just have to modify the openshift express api. But in this case the multiple images come from `ember try:one ...`

**Comment by EWhite613** [comment]
@sglanzer The box is how it looks in Firefox v31.0

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by sglanzer** [comment]
FireFox is up to version 47, so we should modify the travis config to have firefox:latest

**Comment by ember-cli-visual-acceptance** [comment]
PR ember-cli-visual-acceptance Report

**Comment by sglanzer** [comment]
Nice, thanks!

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
