### PR TITLE
Update visual acceptance

### PR DESCRIPTION
**Pull request by EWhite613**
#patch#

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## New

#### Basic-File-Picker
 

#### File-upload

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
